backend/models/Facturacion.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "facturacion".
 *
 * @property integer $id_facturacion
 * @property string $numero_factura
 * @property string $numero_control
 * @property string $monto_iva
 * @property string $monto_islr
 * @property string $monto_subtotal
 * @property string $monto_recibos
 * @property integer $id_user_registro
 * @property integer $id_user_actualizacion
 * @property string $descripcion
 * @property integer $estatus_factura
 * @property integer $id_aseguradora
 * @property string $monto_factura
 * @property string $otro_monto
 * @property string $comentario
 * @property string $fecha_registro
 * @property string $fecha_actualizacion
 * @property string $fecha_factura
 * @property string $fecha_recepcion
 *
 * @property Aseguradoras $idAseguradora
 * @property FacturacionDetalle[] $facturacionDetalles
 * @property InterReciboFactura[] $interReciboFacturas
 */
class Facturacion extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $recibos,$recibos_numero,$aseguradora;
    public static function tableName()
    {
        return 'facturacion';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['numero_factura', 'monto_recibos', 'id_user_registro', 'id_aseguradora', 'fecha_registro','recibos_numero'], 'required'],
            [['numero_factura', 'numero_control', 'monto_iva', 'monto_islr', 'monto_subtotal', 'monto_recibos', 'monto_factura', 'otro_monto'], 'number'],
            [['id_user_registro', 'id_user_actualizacion', 'estatus_factura', 'id_aseguradora'], 'integer'],
            [['descripcion', 'comentario'], 'string'],
            [['fecha_registro', 'fecha_actualizacion', 'fecha_factura', 'fecha_recepcion'], 'safe'],
            [['id_aseguradora'], 'exist', 'skipOnError' => true, 'targetClass' => Aseguradoras::className(), 'targetAttribute' => ['id_aseguradora' => 'id_aseguradora']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_facturacion' => Yii::t('app', 'Id Facturacion'),
            'numero_factura' => Yii::t('app', 'Numero Factura'),
            'numero_control' => Yii::t('app', 'Numero Control'),
            'monto_iva' => Yii::t('app', 'Monto Iva'),
            'monto_islr' => Yii::t('app', 'Monto Islr'),
            'monto_subtotal' => Yii::t('app', 'Monto Subtotal'),
            'monto_recibos' => Yii::t('app', 'Monto Recibos'),
            'id_user_registro' => Yii::t('app', 'Id User Registro'),
            'id_user_actualizacion' => Yii::t('app', 'Id User Actualizacion'),
            'descripcion' => Yii::t('app', 'Descripcion de Recibos'),
            'estatus_factura' => Yii::t('app', 'Estatus Factura'),
            'id_aseguradora' => Yii::t('app', 'Aseguradora'),
            'monto_factura' => Yii::t('app', 'Monto Factura'),
            'otro_monto' => Yii::t('app', 'Otro Monto'),
            'comentario' => Yii::t('app', 'Comentario'),
            'fecha_registro' => Yii::t('app', 'Fecha Registro'),
            'fecha_actualizacion' => Yii::t('app', 'Fecha Actualizacion'),
            'fecha_factura' => Yii::t('app', 'Fecha Factura'),
            'fecha_recepcion' => Yii::t('app', 'Fecha Recepcion'),
            'recibos_numero' => Yii::t('app', 'Numero de Recibos'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdAseguradora()
    {
        return $this->hasOne(Aseguradoras::className(), ['id_aseguradora' => 'id_aseguradora']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFacturacionDetalles()
    {
        return $this->hasMany(FacturacionDetalle::className(), ['id_facturacion' => 'id_facturacion']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInterReciboFacturas()
    {
        return $this->hasMany(InterReciboFactura::className(), ['id_facturacion' => 'id_facturacion']);
    }

    public function afterSave($insert, $changedAttributes)
    {
 		\Yii::$app->db->createCommand()->delete('inter_recibo_factura', 'id_facturacion = '.(int) $this->id_facturacion)->execute();

 		 if(!empty($this->recibos)){
 				foreach ($this->recibos as $id) {
 					$ro = new InterReciboFactura();
					  $re = Recibo::findOne($id);
								$ro->id_facturacion = $this->id_facturacion;
								$ro->id_recibo = $id;
								$ro->save();
					  $re->facturado=1;
					  $re->save();

 				}
 			}

 	   }

     public function getRecibos()
     {
     		return $this->hasMany(Recibo::className(), ['id_recibo' => 'id_recibo'])
     			->viaTable('inter_recibo_factura', ['id_facturacion' => 'id_facturacion']);
     }

     public function getRecibosList()
     {
     		return $this->getRecibos()->asArray();
     }
}

backend/controllers/FacturacionController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Facturacion;
use backend\models\DetalleFactura;
use backend\models\FacturacionDetalle;

use backend\models\search\FacturacionSearch;
use backend\models\search\ReciboSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\models\Poliza;
use backend\models\Recibo;
use yii\data\ActiveDataProvider;
use common\models\MultipleModel as Model;
use yii\helpers\Json;
use yii\web\Response;
use yii\widgets\Pjax;

/**
 * FacturacionController implements the CRUD actions for Facturacion model.
 */
class FacturacionController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

	public function actionRecibos($id)
    {

		$searchModel = new ReciboSearch();
		//print_r(Yii::$app->request->queryParams);exit();
        $dataProvider = $searchModel->search2(Yii::$app->request->queryParams,$_GET['id']);

        return $this->renderAjax('recibos', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Facturacion models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new FacturacionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Facturacion model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Facturacion model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Facturacion();
		    $modelDetalle = [new FacturacionDetalle];

         $modelDetalle = Model::createMultiple(FacturacionDetalle::classname());
         Model::loadMultiple($modelDetalle, Yii::$app->request->post());

        if ($model->load(Yii::$app->request->post())) {

            $recibos=explode(',',$_POST["Facturacion"]['recibos']);
            $model->recibos=$recibos;
            $model->id_user_registro =Yii::$app->user->identity->id;
            $model->fecha_registro=date('Y-m-d H:i:s');
            if($flag=$model->save()){
              if(count($modelDetalle)>0){

                foreach ($modelDetalle as $modelDet) {
     							   $modelDetalle = new FacturacionDetalle;
     							   $modelDetalle->id_facturacion = $model->id_facturacion;
     							   $modelDetalle->descripcion=$modelDet->descripcion;
     							   $modelDetalle->monto=$modelDet->monto;
     							   $flag = $modelDetalle->save();
     					  }

     					  if ($flag = $modelDetalle->save(false)) {

     						}else{
     							var_dump($modelDetalle->getErrors());
     				    }

              }else{
                return $this->redirect(['view', 'id' => $model->id_facturacion]);
              }


      			}else{
      				var_dump($model->getErrors());
      			}

        } else {
            return $this->render('create', [
                'model' => $model,
				'modelDetalle' => (empty($modelDetalle)) ? [new FacturacionDetalle] : $modelDetalle,
            ]);
        }
    }

    /**
     * Updates an existing Facturacion model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
		$modelDetalle = new DetalleFactura($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_facturacion]);
        } else {
            return $this->render('update', [
                'model' => $model,
				'modelDetalle' => $modelDetalle,
            ]);
        }
    }

    /**
     * Deletes an existing Facturacion model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionCargandoRecibos()
    {
        $pk = Yii::$app->request->post('keylist');

        $recibos=Recibo::find()->where("id_recibo IN ($pk)")->select("nro_recibo,comision_vendedor")->asArray()->all();
        $cadena="";
        $recibo="";
        $comision=0;
        foreach ($recibos as $key => $value) {
            $re[]=$value['nro_recibo'];
            $comision+=$value['comision_vendedor'];
        }
         $recibo=implode(',',$re);

        Yii::$app->response->format = Response::FORMAT_JSON;
        return $arrayName = array('recibos' => $recibo,'comision'=>$comision);

    }


    /**
     * Finds the Facturacion model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Facturacion the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Facturacion::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/facturacion/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\FacturacionSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="facturacion-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_facturacion') ?>

    <?= $form->field($model, 'numero_factura') ?>

    <?= $form->field($model, 'numero_control') ?>

    <?= $form->field($model, 'monto_iva') ?>

    <?= $form->field($model, 'monto_islr') ?>
	
	<?= $form->field($model, 'numero_poliza') ?>
	
	<?= $form->field($model, 'nro_recibo') ?>
	
	<?= $form->field($model, 'fecha_vigenciadesde') ?>

    <?php // echo $form->field($model, 'monto_subtotal') ?>

    <?php // echo $form->field($model, 'monto_total') ?>

    <?php // echo $form->field($model, 'id_user_registro') ?>

    <?php // echo $form->field($model, 'id_user_actualizacion') ?>

    <?php // echo $form->field($model, 'fecha_registro') ?>

    <?php // echo $form->field($model, 'fecha_actualizacion') ?>

    <?php // echo $form->field($model, 'descripcion') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/facturacion/create.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\icons\Icon;
use yii\helpers\Url;

$this->title = '';
?>
<div id="bc1" class="btn-group btn-breadcrumb" style="float:right;">
          <a href="#" class="btn btn-default"><i class="fa fa-home"></i></a>
          <a href="<?=Url::to(['index'], true)?>" class="btn btn-default"><div><?=Yii::t('app', 'Facturacion')?></div></a>
          <a href="#" class="btn btn-default"><div>Facturar Comisiones</div></a>
</div>
</br></br>
<div class="facturacion-create">
    <div class="bg-aqua top-modulo">
        <span class="icon-modulo"><i class="fa fa-list-alt fa-3x" aria-hidden="true"></i></span>
        <span style="color:white;font-size:18px;font-weight:bold;"><?=Yii::t('app', 'Crear Factura por Comisiones');?></span>
    </div>

    <?= $this->render('_form',[
                'model' => $model,
				'modelDetalle'=>$modelDetalle,
    ]); ?>

</div>
<?php $string=".top-modulo{padding:2px 2px 2px 8px;}
          .icon-modulo{margin:0px 4px 0px 0px}";
      $this->registerCss($string);
?>

backend/views/facturacion/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use backend\models\Aseguradoras;
use kartik\icons\Icon;
use yii\helpers\Url;
Icon::map($this, Icon::WHHG); // Maps the Elusive icon font framework
Icon::map($this, Icon::FA); // Maps the Elusive icon font framework

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\FacturacionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title ='';//' Yii::t('app', 'Facturacions');
?>
<div id="bc1" class="btn-group btn-breadcrumb" style="float:right;">
           <a href="#" class="btn btn-default"><i class="fa fa-home"></i></a>
</div>
</br></br>
<div class="facturacion-index">

<?php
	$gridColumns = [
    ['class' => 'yii\grid\SerialColumn'],
    [
          'attribute'=>'id_aseguradora',
          'width'=>'300px',
          'value'=>'aseguradora',
          'filterType'=>GridView::FILTER_SELECT2,
          'filter'=>ArrayHelper::map(Aseguradoras::find()->orderBy('nombre')->asArray()->all(), 'id_aseguradora', 'nombre'),
          'filterWidgetOptions'=>[
            'pluginOptions'=>['allowClear'=>true],
            ],
      'filterInputOptions'=>['placeholder'=>'Aseguradoras','id' => 'aseguradoras-select2-id'],
    ],
    [
      'attribute'=>'numero_factura',
      'value'=>'numero_factura',
      'width'=>'200px',
    ],
    ['class' => 'kartik\grid\DataColumn',
     'attribute'=>'fecha_factura',
     'width'=>'200px',
     'value'=>function ($model) {
               if($model->fecha_factura!=""){
                 return date("d-m-Y", strtotime($model->fecha_factura));
               }else{
                 return "";
               }

      },
     'filterType'=>GridView::FILTER_DATE,
     'filterWidgetOptions' => [
        'pluginOptions'=>[
        'format' => 'dd-mm-yyyy',
        'autoWidget' => true,
        'autoclose' => true,
        //'todayBtn' => true,
        ],

      ],
    ],
    [
      'attribute'=>'monto_factura',
      'value'=>'monto_factura',
      'width'=>'200px',
    ],
    [
      'attribute'=>'descripcion',
      'value'=>'descripcion',
      'width'=>'500px',
    ],

    [
    'class'=>'kartik\grid\BooleanColumn',
    'filterType'=>GridView::FILTER_SELECT2,
    'attribute'=>'estatus_factura',
    'vAlign'=>'middle',
    'width'=>'150px',
    ],
    [
     'class' => 'yii\grid\ActionColumn',
     'contentOptions' => ['style' => 'width:200px;'],
     'header'=>'GESTION FACTURA',
     'template' => '{view} {update}',
      'buttons' => [
              'view' => function ($url,$model, $key) {
                return Html::a('<i class="fa fa-binoculars fa-lg" aria-hidden="true"></i>', ['facturacion/view','id' => $model->id_facturacion], [
                    'id' => 'activity-index-link-view',
                    'title' => Yii::t('app', 'Ver poliza'),'rel'=>'tooltip',
                    'data-pjax' => '0',
                ]);
              },
             'update' => function ($url,$model, $key) {
                       return Html::a('<i class="fa fa-pencil fa-lg" aria-hidden="true"></i>', ['facturacion/update','id' => $model->id_facturacion], [
                           'id' => 'activity-index-link-update',
                           'title' => Yii::t('app', 'Actualizar Poliza'),'rel'=>'tooltip',
                           'data-pjax' => '0',
                       ]);
                      },
           ]
    ],
	];

	echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
		    'columns' => $gridColumns,
		    'containerOptions' => ['style'=>'overflow: auto'], // only set when $responsive = false
    		'toolbar' => [
    			[
    				'content'=>
    					Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'],[
    						//'type'=>'button',
    						'title'=>Yii::t('app', 'Registrar Factura'),
    						'class'=>'btn btn-success'
    					]) . ' '.
    					Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['index'], [
    						'class' => 'btn btn-default',
    						'title' => Yii::t('app', 'Reset Grid')
    					]),

    			],
    			'{export}',
    			'{toggleData}'
    		],
        'exportConfig' => [
          GridView::EXCEL => [],
          GridView::TEXT => [],
          GridView::PDF => [],
        ],

		'pjax' => false,
		'pjaxSettings' => [
			'options' => ['id' => 'facturacion-pjax-id'],// UNIQUE PJAX CONTAINER ID
		],
		'bordered' => false,
		'resizableColumns'=>true,
		'resizeStorageKey'=>Yii::$app->user->id . '-' . date("m"),
		'striped' => true,
		'condensed' => false,
		'responsive' => true,
		'hover' => true,
		'showPageSummary' => false,
		'panel' => [
      'heading'=>'<h2 class="panel-title" style="font-weight:bold;">'.Icon::show('cashregister', ['class'=>'icon'], Icon::WHHG).'&nbsp; &nbsp;FACTURAS DE COMISIONES</h2>',
      'type' => GridView::TYPE_INFO
		],
    ]);
	?>

</div>
<?php

$string = <<<EXP2
$("[rel=tooltip]").tooltip({ placement: 'top'});

EXP2;
$this->registerJs($string, \yii\web\View::POS_READY);

?>

<?php

$string='
@brand-success: #5cb85c;
@brand-info:    #5bc0de;
@brand-warning: #f0ad4e;
@brand-danger:  #d9534f;

.icon-cashregister{
       font-size: 150%;

}
.fa{margin:0px 4px 0px 0px;}
 .fa-bars{
     color:  #d9534f;
 }
 .fa-card{
     color:  #5cb85c;
 }
 .fa-money{
     color:  #5bc0de;
 }

 ';
$this->registerCss($string);
?>

backend/views/facturacion/recibos.php
<?php

use yii\helpers\Html;
//use yii\grid\GridView;
use yii\helpers\Url;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use backend\models\Poliza;
use kartik\icons\Icon;
use kartik\daterange\DateRangePicker;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\PolizaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

//http://www.w3schools.com/colors/colors_picker.asp colores
$this->title = "";
?>
<?php Pjax::begin(['id' => 'recibos-pjax-id','timeout' => false,'enablePushState' => false]) ?>
<div class="recibos-modal-index">
    <?php
  	$gridColumns = [
  	//['class' => 'kartik\grid\SerialColumn'],
		[
			 'class'=>'kartik\grid\CheckboxColumn',
       'checkboxOptions' => function ($model, $key, $index, $column) {
          return ['value' => $model->numero_poliza];
       },
		],
    [
          'class' => 'kartik\grid\DataColumn',
          'attribute'=>'numero_poliza',
          'value'=>'numero_poliza',
          'width'=>'200px',
    ],
	 /* [
            'class' => 'kartik\grid\DataColumn',
            'attribute'=>'aseguradora',
            'value'=>'aseguradora',
            'width'=>'300px',
     ],*/
	  [
          'class' => 'kartik\grid\DataColumn',
          'attribute'=>'nro_recibo',
          'value'=>'nro_recibo',
          'width'=>'200px',
    ],
		[
            'attribute' => 'fecha_vigenciadesde',
            'value' => 'fecha_vigenciadesde',
            'format'=>'raw',
            'options' => ['style' => 'width: 25%;'],
            'filter' => DateRangePicker::widget([
                'model' => $searchModel,
                'attribute' => 'fecha_vigenciadesde',
                'useWithAddon'=>false,
                'convertFormat'=>true,
                'pluginOptions'=>[
                    'locale'=>['format'=>'Y-m-d']
                ],
            ])
        ],
        [
              'class' => 'kartik\grid\DataColumn',
              'attribute'=>'comision_total',
              'value'=> 'comision_total',
              'width'=>'200px',
        ],
  	];
 ?>


 <?php

  	echo GridView::widget([
	   'id'=>'recibos-gridview-id',
       'dataProvider' => $dataProvider,
       'filterModel' => $searchModel,
  		'columns' => $gridColumns,
  		'containerOptions' => ['style'=>'overflow: auto'], // only set when $responsive = false
        'rowOptions' => function ($model, $key, $index, $grid) {
           return ['id' =>$key,'data-recibo'=>$model->id_recibo,'class' => GridView::TYPE_INFO];
        },//'rbo-'+$key
  		'toolbar' => [
  			'{export}',
  			'{toggleData}'
  		],

  	/*'pjax' => true,
		'pjaxSettings'=>[
           'options'=>[
            'enablePushState'=>false,
            'id'=>'recibos-pjax-id',// UNIQUE PJAX CONTAINER ID
            'formSelector'=>'ddd',
          ],
      ],*/
  		'bordered' => false,
  		'resizableColumns'=>true,
  		'resizeStorageKey'=>Yii::$app->user->id . '-' . date("m"),
  		'striped' => true,
  		'condensed' => false,
  		'responsive' => true,
  		'hover' => true,
  		'showPageSummary' => false,
    		'panel' => [
          'heading'=>'<h2 class="panel-title">&nbsp; &nbsp;Recibos</h2>',
    			'type' => GridView::TYPE_INFO
    		],
      ]);
 ?>

<?php Pjax::end() ?>
</div>
<div class="form-group" style="float:left"><!--INICIO BOTONES DEL PANEL-->
<?= Html::Button(Icon::show('more').'Incluir Recibos en la Facturacion', ['class' => 'btn btn-primary','id' =>'cargar-recibos']) ?>
</div><!--FIN BOTONES DEL PANEL-->


<?php
$string = <<<EXP2

$("#cargar-recibos").on("click", function() {
        var keys = $("#recibos-gridview-id").yiiGridView('getSelectedRows');
        var recibos="";
        $.each(keys,function( k, v ) {
           recibos += v+',';
        });
        recibos=recibos.slice(0,-1);
        if(recibos!=''){
           $("#facturacion-recibos").val(recibos);
           $.post("cargando-recibos", { keylist: recibos })
           .done(function(result) {
			   
              $("#facturacion-recibos_numero").val(result.recibos);
            
				
			  $("input[id*='monto_']").not( "#facturacion-monto_iva-disp,#facturacion-monto_iva").val(parseFloat(result.comision).toFixed(2));
				
			 
			  
           });//.donefunction(result)
         $('#modal').modal('hide');
        }else{
          alert('Debe seleccionar al menos un recibo');
        }

});
//data-col-seq
EXP2;
$this->registerJs($string, \yii\web\View::POS_READY);
$string='';
$this->registerCss($string);
?>

backend/views/facturacion/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Facturacion */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Facturacion',
]) . ' ' . $model->id_facturacion;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Facturacions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_facturacion, 'url' => ['view', 'id' => $model->id_facturacion]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="facturacion-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/facturacion/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Facturacion */

$this->title = $model->id_facturacion;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Facturacions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="facturacion-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id_facturacion], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id_facturacion], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_facturacion',
            'numero_factura',
            'numero_control',
            'monto_iva',
            'monto_islr',
            'monto_subtotal',
            'monto_recibos',
            'id_user_registro',
            'id_user_actualizacion',
            'fecha_registro',
            'fecha_actualizacion',
            'descripcion:ntext',
        ],
    ]) ?>

</div>